language: clojure
before_install:
 - sudo apt-get install python2.7
 - pip install pyopenssl ndg-httpsclient pyasn1
 - pip install awscli
addons:
  artifacts:
    debug: true
after_success:
 - echo "done!"